### ISSUE TITLE
chore: establish formatting/linting styles

### ISSUE THREAD

**Issue by elijaholmos** [crimlog/api#5]
## Formatting
- [x] Select a formatting tool
- [x] Define a project-level formatter configuration file 
- [x] Integrate the formatting tool into CI

## Linting
- [x] Select a linting tool
- [x] Define a project-level linting configuration file 
- [x] Integrate the linting tool into CI

**Comment by melzs0627** [comment]
## Testing
- [x] Approve selected formatting tool
- [x] Approve selected linting tool
- [x] Approve configuration file changes
- [x] Approve Integrated linting tool into CI
